### ISSUE TITLE
feat: adicionar múltiplas signatures no certificado

### ISSUE THREAD

**Issue by luandadantas** [exageraldo/certifigo#2]
Criar a possibilidade de termos múltiplas pessoas responsáveis em assinar o certificado, a alteração seria feita nos campos `signature` e `signature-img`

**Comment by exageraldo** [comment]
Muito obrigado @luandadantas por abrir a issue!

## Contexto

Esses valores são definidos em três momentos: flags no comando [`certifigo generate attendee`](https://github.com/exageraldo/certifigo/blob/4669122da6316692e8ecb045bd795395cea64a3c/cmd/cli/generate.go#L72), flags no comando [`certifigo generate speaker`](https://github.com/exageraldo/certifigo/blob/4669122da6316692e8ecb045bd795395cea64a3c/cmd/cli/generate.go#L145) e parseados do arquivo TOML no comando [`certifigo generate from-file`](https://github.com/exageraldo/certifigo/blob/4669122da6316692e8ecb045bd795395cea64a3c/event_file.go#L3)

Algo mais ou menos assim:
```go
// attendee
generateAttendeeCmd.Flags().StringVar(&EventFromCLI.Signature, "signature", "", "Name of the signature")
generateAttendeeCmd.Flags().StringVar(&EventFromCLI.SignatureImg, "signature-img", "", "Signature image path")

// speaker
generateSpeakerCmd.Flags().StringVar(&EventFromCLI.Signature, "signature", "", "Name of the signature")

// from-file
type Event struct {
	// ...
	Signature    string `toml:"signature"`
	SignatureImg string `toml:"signature_img"`
	// ...
}
```

Atualmente o comando está dessa forma:
```shell
certifigo generate attendee \
    # omitindo outras flags obrigatorias
    --signature="Nome da Pessoa Assinante" \
    --signature-img="caminho/para/assinatura.png"
```

E para definir no arquivo TOML:
```toml
[event]
# omitindo outras flags obrigatorias
signature="Nome da Pessoa Assinante"
signature_img="caminho/para/assinatura.png"
```

O ponto de maior atenção é nas informações passadas direto como flags dos comandos, pois como temos que agregar duas informações (nome e assinatura de uma mesma pessoa), fica um pouco mais difícil de agregarmos uma lista de assinaturas com uma lista de imagens de assinatura.

Podemos definir esses valores como listas, e receber mais de um valor mais ou menos assim:
```shell
certifigo generate attendee \
    # omitindo outras flags obrigatorias
    --signature="Nome da Pessoa Assinante Um" \
    --signature-img="caminho/para/assinatura-um.png" \
    --signature="Nome da Pessoa Assinante Dois" \
    --signature-img="caminho/para/assinatura-dois.png"
```

Mas começam a aparecer algumas duvidas como: será que podemos confiar que a ordem vai estar realmente correta (`Nome da Pessoa Assinante Um` -> `caminho/para/assinatura-um.png` e `Nome da Pessoa Assinante Dois` -> `caminho/para/assinatura-dois.png`)? Caso possa ser realmente garantido, vem um ponto mais chatinho, que é quando não queremos definir imagens para todos os comandos. Por exemplo, vamos dizer que queremos definir imagem apenas para a segunda assinatura (`Nome da Pessoa Assinante Dois`), teríamos que passar um caminho de imagem vazio (e validar isso via código) ou documentar que as primeiras imagens serão associadas as primeiras assinaturas listadas. O que eu não sei se nenhuma das abordagens são viáveis.

## Ideias

Uma ideia que tive é de "unificarmos" esses dois valores/informações em uma única flag, algo como temos parecido para definir a opacidade de cores (`#RRGGBB[100%]`).

Ficaria algo mais ou menos assim:
```shell
certifigo generate attendee \
    # omitindo outras flags obrigatorias
    --signature="Nome da Pessoa Assinante[caminho/para/assinatura.png]" \
    --signature="Nome da Pessoa Assinante Dois[caminho/para/assinatura-dois.png]"
```

```toml
[event]
# omitindo outras flags obrigatorias

[[signatures]]
name="Nome da Pessoa Assinante"
img="caminho/para/assinatura.png"

[[signatures]]
name="Nome da Pessoa Assinante Dois"
img="caminho/para/assinatura-dois.png"
```

E quando não quisermos definir uma imagem para a assinatura, basta omitir a informação:
```shell
certifigo generate attendee \
    # omitindo outras flags obrigatorias
    --signature="Nome da Pessoa Assinante" \
    --signature="Nome da Pessoa Assinante Dois[caminho/para/assinatura-dois.png]"
```

```toml
[event]
# omitindo outras flags obrigatorias

[[signatures]]
name="Nome da Pessoa Assinante"

[[signatures]]
name="Nome da Pessoa Assinante Dois"
img="caminho/para/assinatura-dois.png"
```

## Observações

- Sei que é uma "braking change" (por estarmos mudando a interface de interação com o usuário), mas como ainda não lançamos nenhuma versão estável, acredito que não tenha problema de fazermos essas mudanças.
- Ao escrever essa mensagem, percebi que o comando de gerar o certificado de palestrante (`generateSpeakerCmd`) não está definindo a flag `signature-img`.

Duas perguntas:
- Quantas assinaturas no máximo aceitaremos?
- O que você acha das coisas que falei aqui? 😄
